### ISSUE TITLE
Updates to Install Vivado/Vitis page

### ISSUE THREAD

**Issue by benbroce** [byu-cpe/ComputingBootCamp#119]
Version 2020.2 is now in archive (https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/vitis/2022-1.html). If it is not important which version is used, perhaps we should point to a newer version or simply say "find the section for the latest Vitis Core Development Kit - Full Product Installation"

**Comment by jgoeders** [comment]
I think we can continue to point to 2020.2.  Would you mind updating the link and creating a PR?
