### ISSUE TITLE
Links to Navigate Site broken?

### ISSUE THREAD

**Issue by DanielChaseButterfield** [byu-cpe/ComputingBootCamp#127]
Is it just me, or did all of the module buttons (like "Software Development", "Commercial FPGA", etc.) stop working?

This is preventing me from accessing any of the tutorials easily.

**Comment by jgoeders** [comment]
Works for me.  Do you have javascript disabled?

**Comment by DanielChaseButterfield** [comment]
Hmm, now it's working for me too. Weird fluke for me then.
