### ISSUE TITLE
Carifications for Setting up Webpage

### ISSUE THREAD

**Issue by masterqwerty** [byu-cpe/ComputingBootCamp#18]
There are a few items that I think need clarifying on this tutorial:
* I would mention that you have to have an SSH key associated with your GitHub account if you're going to use the `git@github.com` URL to clone a repository.
* Apparently, you have to be on a paid plan to have your repository be private and host GitHub pages from your repo, so I would probably mention that in the tutorial where it says that it doesn't matter whether the repo is public or private.
* This one's really nit-picky, but I would mention at the end that it takes a minute or two for the page to actually publish once you push to the repo.

**Comment by jgoeders** [comment]
Assign to @WhiteNinjaZ
