### ISSUE TITLE
[SUGGESTION] Remove Scroll Bar on Left Sidebar when tabs are open

### ISSUE THREAD

**Issue by DlittlemanDungeon** [byu-cpe/ComputingBootCamp#47]
I think that the Left Sidebar looks very clean, especially when you first open the computing bootcamp page. However, once you open a tab, a scroll bar pops up with it, that gives it a much more dated or unprofessional feel. I think it would be better if you could scroll up and down on the Left Sidebar without the Scroll Bar appearing. 

Reasons for it:
 - I think that most people would understand that the Left Sidebar can scroll up and down without the Scroll Bar being there, and (in my opinion) it looks alot cleaner, newer, and more professional without it.

 - After opening up a tab on the Left Sidebar, and then using the widget with three horizontal lines in the upper left hand corner to collapse the Left Sidebar, the Scroll Bar still remains on the left side of the page, which I don't think is intentional. Removing the bar completely would solve this issue.

Reasons against it:
 - Might be hard to implement, maybe Jekkel would complicate it.

 - Some people might like the look of the Scroll Bar.

Reference image of the Left Sidebar with the Scroll Bar attached:
![Untitled](https://user-images.githubusercontent.com/77311063/118876114-18812500-b8aa-11eb-8807-164026f7ff73.png)

Reference image of the Left Sidebar WITHOUT the Scroll Bar attached:
![Untitled](https://user-images.githubusercontent.com/77311063/118876348-6302a180-b8aa-11eb-8479-750692766a87.png)

**Comment by jgoeders** [comment]
Changed in 0cff827d22357d5e671e44fab930e757fc581905

**Comment by jgoeders** [comment]
Never mind, that got rid of the scroll bar, but then I couldn't scroll.  Looks like the solution is here.  https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll, but I'm out of time at the moment.

**Comment by DlittlemanDungeon** [comment]
Sweet!
